package linq.exception

enum class ExceptionArgument(val string: String) {
    CollectionSelector("collectionSelector"),
    Count("count"),
    ElementSelector("elementSelector"),
    Enumerable("enumerable"),
    First("first"),
    Func("func"),
    Index("index"),
    Inner("inner"),
    InnerKeySelector("innerKeySelector"),
    KeySelector("keySelector"),
    Outer("outer"),
    OuterKeySelector("outerKeySelector"),
    Predicate("predicate"),
    ResultSelector("resultSelector"),
    Second("second"),
    SeedSelector("seedSelector"),
    Selector("selector"),
    Source("source"),
    Third("third"),
    Size("size"),
    Other("other"),
    Start("start"),
    Step("step"),
    EndInclusive("endInclusive"),
}
